# Escalas de medición o clasificación

El nivel de medición o la escala de medición es una clasificación que identifica la naturaleza de la información dentro de los números asignados a las variables. El psicólogo Stanley Smith Stevens desarrolló la clasificación más conocida con cuatro niveles, o escalas, de medida: nominal, ordinal, intervalo y de razón. [@stevens1946theory] Este marco de distinción de los niveles de medición se originó en la psicología y es ampliamente criticado por los académicos de otras disciplinas [@michell1986measurement]. Otras clasificaciones incluyen las de Mosteller y Tukey, [@mosteller1977data] y la de Chrisman. [@chrisman1998rethinking].

# Tipología de Stevens

El profesor Stevens propuso su tipología en un artículo titulado "On the theory of scales of measurement"[@stevens1946theory], publicado en la revista _Science_. En ese artículo se afirma que toda la medida en la ciencia se ha hecho usando cuatro tipos diferentes de escalas a las que llamó _nominal_, _ordinal_, _de intervalo_ y _de razón_, unificando tanto las _cualitativas_ (descritas por él como de tipo _nominal_) y las _cuantitativas_ (el resto de sus escalas).

El concepto de _tipos de escala_ recibió todo el rigor formal del que carecía en su inicio con el trabajo matemático de los psicólogos Theodore Alper[@alper1985note; @alper1987classification], Louis Narens[@narens1981general; @narens1981scales] y Robert Duncan Luce[@luce1986uniqueness; @luce1987measurement]. De hecho Luce [@luce2001conditions] escribió:

> S.S. Stevens [@stevens1946theory; @stevens1951mathematics; @stevens1975psychophysics] afirmó que al contar se tenía una escala de intervalo o de razón. Investigaciones posteriores han dado sentido a esta afirmación pero debido a sus intentos de invocar las ideas de tipo de escala es dudoso si se entendía a sí mismo... sé que ningún teórico de la medición acepta la amplia definición  de medición dada por Stevens... en nuestra opinión, el único significado sensato de 'regla' es empíricamente comprobable por las leyes que se le atribuyen.

## _Comparación_

A continuación se presenta una comparación entre las distintas escalas propuestas por Stevens.

| Escala    | Propiedad de medida       | Operadores matemáticos | Operaciones avanzadas | Tendencia central                          |
|-----------|---------------------------|------------------------|-----------------------|--------------------------------------------|
| Nominal   | Clasificación, afiliación | =, !=                  | Agrupamiento          | Moda                                       |
| Ordinal   | Comparación, nivel        | >, <                   | Ordenamiento          | Mediana                                    |
| Intervalo | Diferencia, afinidad      | +, -                   | Indicador             | Media, Desviación                          |
| Razón     | Magnitud, cantidad        | *, /                   | Cociente              | Media Geométrica, Coeficiente de variación |

## _Escala nominal_

El tipo nominal diferencia entre objetos o temas basándose únicamente en sus nombres o (meta-)categorías  y otras clasificaciones cualitativas a la que pertenecen; por lo tanto los datos dicotómicos involucran la construcción de clasificaciones, así como la clasificación de los objetos. El descubrimiento de una excepción a la clasificación puede ser vista como un progreso. Los números pueden ser usados para representar las variables, pero los números no tienen valor numérico o relación: por ejemplo, un identificador único global.

Ejemplos de estas clasificaciones son el sexo, nacionalidad, origen étnico, idioma, género, estilo, especies biológicas, y la forma. 

Las escalas nominales fueron llamados a menudo escalas cualitativas, y las medidas tomadas en escalas cualitativas fueron llamados datos cualitativos. Sin embargo, el aumento de la investigación cualitativa ha hecho confuso este uso. Los números en la medida nominal se asignan como etiquetas y no tienen valor numérico específico o significado. Ningún cálculo matemático (+, -, x, etc.) puede realizarse de medidas nominales. El nivel nominal es la medición de nivel más bajo utilizado desde un punto de vista estadístico.

### Operaciones matemáticas

La igualdad y otras operaciones que puedan ser definidas en términos de igualdad, tales como desigualdad y pertenencia son las únicas operaciones no triviales que genéricamente pueden aplicarse a objetos de tipo nominal.

### Medidas de tendencia central

La moda es una medida de tendencia central que se acepta en la escala de tipo nominal. Por otra parte, la mediana no tiene sentido en esta escala puesto que la clasificación no tiene sentido para el tipo nominal.

## _Escala ordinal_

El tipo ordinal obedece a una estructura matemática de orden (primero, segundo, tercero, etc.) mediante la cual los datos pueden ser ordenados, pero todavía no permite un grado de diferencia entre ellos. Los ejemplos incluyen, por un lado, los datos dicotómicos con valores dicotómicos (o dicotomizadas) tales como 'enfermo' vs. 'saludable' en la medición de la salud, 'culpable' vs. 'inocente' al hacer juicios en los tribunales, 'equivocado/falso' vs. 'correcto/verdadero' en la medición de la verdad justa, y, por otro lado, no dicotómicas de datos que constan de un espectro de valores, tales como 'completamente de acuerdo', 'mayormente de acuerdo', 'mayormente en desacuerdo', 'completamente en desacuerdo' cuando se mide la opinión.

### Medidas de tendencia central

La mediana y la moda se permiten como medidas de tendencia central mientras que la media (el promedio), no se permite.

En 1946, Stevens observó que la medición psicológica, tal como la medición de opiniones, por lo general funciona con escalas ordinales; por lo tanto, las medias y las desviaciones estándar no tienen validez, sino que se pueden utilizar para obtener ideas sobre cómo mejorar la operacionalización de las variables utilizadas en los cuestionarios. La mayoría de los datos psicológicos recogidos por los instrumentos psicométricos y pruebas, medición y otras habilidades cognitivas, son ordinales, aunque algunos teóricos han argumentado que puedan ser tratados como escalas de intervalo o de razón. Sin embargo, hay poca evidencia _prima facie_ que sugiera que tales atributos son algo más que ordinales[@cliff2003ordinal; @cliff2014ordinal; @michell2008psychometrics]. En particular, las puntuaciones de CI reflejan una escala ordinal, en los cuales todos los resultados son significativos sólo para comparación[@lord1968statistical]. No hay cero absoluto, y una diferencia de 10 puntos puede llevar a diferentes significados en diferentes puntos de la escala.

## _Escala de intervalo_

El tipo de escala de intervalo permite el _grado de diferencia_ entre los elementos, pero no la relación entre ellos. Los ejemplos incluyen la _temperatura_ con escala Celsius, que tiene dos puntos definidos (el punto de congelación y ebullición del agua a condiciones específicas) y luego separados en 100 intervalos, las _fechas_ cuando se miden desde una época arbitraria (tales como AD), el _porcentaje_ tal como un porcentaje de retorno de un valor, la _ubicación_ en coordenadas cartesianas, y la _dirección_ que se mide en grados a partir del norte verdadero o magnético. Las proporciones no son significativas puesto que 20°C no puede decirse que sea "dos veces más caliente", que 10°C, ni la multiplicación/división puede realizarse entre dos fechas directamente. Sin embargo, las _razones de diferencias_ pueden ser expresadas; Por ejemplo, una diferencia puede ser el doble de la otra. Las variables de tipo de intervalo a veces también se denominan "variables de escala", pero el término matemático formal es un espacio afín (en este caso una línea análoga).

### Tendencia central y dispersión estadística

La moda, la mediana y la media aritmética se permite medir como medidas de tendencia central de variables en la escala de intervalo, mientras que las medidas de dispersión estadística incluyen el rango y la desviación estándar. Debido a que que sólo se puede dividir por diferencias, no es posible definir medidas que requieran una serie de razones, como el coeficiente de variación. De manera más sutil, mientras que se pueda definir momentos sobre el origen, sólo los momentos centrales son significativos, ya que la elección del origen es arbitraria. Pueden definirse momentos estandarizados, desde que las razones de las diferencias sean significativas, pero no se puede definir el coeficiente de variación, ya que la media es un momento sobre el origen, a diferencia de la desviación estándar, que es (la raíz cuadrada de) un momento central.

## _Escala de razón_

El tipo de escala de razón toma su nombre del hecho de que la medición es la estimación de la relación entre una magnitud de una cantidad continua y una magnitud unitaria de la misma clase [@michell1997quantitative; @michell1999measurement]. Una escala de razón posee un significado (único y no arbitrario) del valor cero. La mayoría de mediciones en las ciencias físicas y la ingeniería se hace en escalas de razón. Los ejemplos incluyen masa, longitud, duración, ángulo del plano, energía y la carga eléctrica. En contraste con las escalas de intervalo, las proporciones son ahora significativas puesto que tener un punto cero no arbitrario  hace que sea significativo decir, por ejemplo, que un objeto tiene "dos veces la longitud" de otro. Muy informalmente, muchas escalas de razón se pueden describir como la especificación de "cuánto hay" de algo (es decir, una cantidad o magnitud) o "cuántos hay" (a cuenta). La escala de temperatura Kelvin es una escala de razón porque tiene un único punto cero no arbitrario, llamado cero absoluto.

### Tendencia central y dispersión estadística

La media geométrica y la media armónica se permiten para medir la tendencia central, además de la moda, la mediana y la media aritmética. El rango estudentizado y el coeficiente de variación permiten medir la dispersión estadística. Todas las medidas estadísticas se permiten porque todas las operaciones matemáticas necesarias se definen para la escala de razón.

# Tipologías en debate con la de Stevens

Mientras la tipología de Stevens está ampliamente adoptada, sigue siendo desafiada por otros teóricos[@michell1986measurement], en particular en los casos de los tipos nominales y ordinales[@velleman1993nominal]. 

Luce [@luce1986uniqueness] se opuso al uso de la palabra _medición_ en relación con el tipo nominal, pero Stevens [@stevens1975psychophysics] dice de su propia definición de medición que "la asignación puede ser cualquier regla consistente. La única regla no permitida sería la asignación aleatoria, para cantidades aleatorias, lo que no sería una regla". Sin embargo, la llamada _medición nominal_ involucra asignación arbitraria, y la "transformación permitida" es cualquier número en otro. 

El uso de la media como una medida de la tendencia central para el tipo ordinal es aún discutible entre quienes aceptan la tipología de Stevens. De todos modos, muchos científicos del comportamiento utilizan la media para datos ordinales. Esto se justifica a menudo sobre la base de que el tipo ordinal en la ciencia del comportamiento está, de hecho, en algún lugar entre los ordinales verdaderos y los tipos de intervalo; a pesar de que la diferencia de intervalo entre dos rangos ordinales no es constante, a menudo es del mismo orden de magnitud.

Por ejemplo, las aplicaciones de los modelos de medición en contextos educativos a menudo se refieren a que las puntuaciones totales tienen una relación bastante lineal con mediciones en el rango de una evaluación. Por lo tanto, algunos argumentan que tanto el tiempo como la diferencia desconocida del intervalo entre rangos de escala ordinal no es muy variable, las estadísticas de escala de intervalo tales como las medias cobran sentido en variables de escala ordinal. 

L. L. Thurstone avanzó hacia el desarrollo de una justificación para obtener el tipo de intervalo, basado en la ley de juicio comparativo[@thurstone1927law]. Un mayor progreso fue hecho por Georg Rasch [@rasch1993probabilistic], que desarrolló el modelo de Rasch probabilístico que proporciona una base teórica y la justificación de la realización de mediciones de nivel de intervalo de frecuencias de observaciones como las puntuaciones totales de las evaluaciones.
