# Indicadores 

Este capítulo se basa especialmente en el trabajo de @perez2002que, @martinez2010indicadores, @rizo2005diseno y @salas2011sistema y se enfoca en indicadores sobre temas educativos.

## Definición

No existe una definición concreta, por parte de organismo alguno sobre los indicadores, algunos de los más importantes son los que se presentan a continuación. 

La Organización de las Naciones Unidas (ONU) definen los indicadores como: 

> "Herramientas para clarificar y definir, de forma más precisa, objetivos e impactos (...) son medidas verificables de cambio o resultado (...) diseñadas para contar con un estándar contra el cual evaluar, estimar o demostrar el progreso (...) con respecto a metas establecidas, facilitan el reparto de insumos, produciendo (...) productos y alcanzando objetivos". [@assembly1999report]

De igual forma, Bauer en 1966 utiliza una definición que utilizan muchos autores:

> “Los indicadores (...) son estadísticas, serie estadística o cualquier forma de indicación que nos facilita estudiar dónde estamos y hacia dónde nos dirigimos con respecto a determinados objetivos y metas, así como evaluar programas específicos y determinar su impacto”. [@horn1993statistical]

Algo interesante es que la Organización para la Cooperación y Desarrollo Económicos - OECD tiene un programa para la información relevante y precisa sobre la educación a nivel mundial. Infortunadamente, Colombia no hace parte de los miembros de este programa denominado *The Indicators of Education Systems (INES) programme*.

Los indicadores son variables o instrumentos de medida que intentan representar un constructo generalmente de forma cuantitativa. Compara entre dos o más tipos de datos para elaborar una _medida cuantitativa_ o una _observación cualitativa_. Dicha comparación arroja un valor, una magnitud o un criterio dotado de un significado para quien lo analiza. Este resultado puede ser usado para escribir y comprender el funcionamiento de la calidad de un sistema o una actividad en concreto.

Su importancia radica en que nos encontramos inmersos en una cultura en el que se privilegia el valor asignado a los objetos, logros o situaciones que sólo adquieren sentido con respecto al valor relativo de las cosas y ese valor puede medirse mediante los indicadores.

## Características de los indicadores 

* Pertenecer a un marco conceptual o teórico que lo dote de sentido. De ser posible, debe establecerse una estructura que lo ubique en un marco explicativo i.e. modelo presión-estado-respuesta (PER) que usa la OECD para los indicadores medio ambientales.

* Ser específicos bajo la naturaleza del tema que se pretenda medir. Debe medir objetivos o metas claros.

* Ser explícitos en el sentido de que su nombre de una idea precisa de si se trata de un valor relativo o absoluto, de una tasa, de una razón, de un índice, etc. De igual forma debe especificar la población de interés, si la información es global o está desagregada por sexo, edad, años, etc.

* Ser perdurable para poder compararlos a través del tiempo

* Ser relevantes y oportunos con el fin de que describan con precisión la situación del fenómeno observable con el fin de establecer acciones.

* Comúnmente un indicador solo no permite la medición completa de un fenómeno por lo que pertenece a una batería de indicadores que en conjunto permiten analizar apropiadamente una situación de estudio.

* Ser claro, fácil de comprender. Para cada indicador se acostumbra tener una definición, fórmula de cálculo y metadatos para su mejor entendimiento y socialización. 

* Ser confiable y consistente en su metodología de cálculo con el fin de que distintas personas, con diferentes herramientas, en circunstancias similares puedan medirlo.

* Ser trazable para que pueda hacerse seguimiento a través del tiempo.

* Ser válido, confiable, comparable y factible en términos de que su costo sea razonable.

* Ser sensible a cambios del fenómeno

* Deben ser medibles a partir de un acervo de datos disponible

## Diferencia entre datos, medidas, estadísticas e indicadores 

* **Dato**: es sólo el insumo para el proceso de construcción de conocimiento y/o estadísticas. El dato *per se* está desprovisto de sentido y su significado se lo provee el contexto en el que se enmarca. Únicamente de esta forma se convierte en *información*.

* **Medida**: impone parámetros de cuantificación (peso, volumen, cantidad, etc.). Permite evaluar la importancia de un objeto o fenómeno comparándolo con otro de la misma especie. Mediante las medidas, los objetos permiten ser claramente procesados y valorados. Todos los indicadores son medidas mas no todas las medidas son indicadores puesto que no todas las medidas indican algo en sentido utilitario y semántico.

* **Estadística**: las estadísticas tienen numerosos propósitos tales como el conteo, medida y descripción de un fenómeno. Se caracterizan por ser exhaustivas, permanentes, técnicas y orientadoras de los procesos para su obtención. Para que una estadística pueda considerarse indicador esponda a ciertos requerimientos
de información representativos del desarrollo económico, social o humano. La construcción de indicadores requiere un marco legal, programático y normativo (nacional y/o internacional)
que establece las necesidades de información para medir o analizar la situación de la educación, economía, la sociedad, la población o el medio ambiente, respecto a determinados valores o metas perseguidos.

* **Indicadores**: sus características son:

    + Ser exclusivo de los temas de política o de administración
    + Ser dinámicos y estar sometidos a continua revisión
    + Ser materia de política pública, de modo que su definición no sea tarea exclusiva de los estadísticos
    + Ser relevantes para la toma de decisiones y definición de políticas
    + Ser oportuno para la evaluación y monitoreo de los asuntos de administración pública o privada
    + Ser analítico de los fenómenos bajo observación
    + Ser comparativo tanto en el tiempo como en el espacio, por lo cual tienen que estar disponibles para diferentes regiones o países y para cada año en un periodo de tiempo determinado.

## Tipos de indicadores

Pueden diferenciarse dos criterios para clasificar los indicadores:

* A partir de la dimensión que se quiere expresar (educativa, social, económica, etc.). Estas dimensiones únicamente difieren por las unidades de medida que usan, así, los indicadores económicos suelen utilizar productos y/o unidades monetarias, los indicadores sociales lo hacen en personas, etc.
  Naturalmente puede hablarse de **indicadores positivos** o **negativos** si se pretenden destacar los avances o rezagos de algún fenómeno de estudio. En este sentido, por ejemplo, puede hablarse de índice de alfabetismo o analfabetismo. De la misma manera existen **indicadores indeterminados**  que son aquellos de los cuales no puede esperarse que alcancen su valor superior o inferior i.e. tasa de matrícula en educación superior, en el sentido de que, si bien se espera que alcance el 100%, no necesariamente es positivo puesto que es imposible que toda la población alcance este nivel de estudios.
  También existen **indicadores absolutos** y **relativos** que son aquellos cuya evaluación depende de un valor determinado (un máximo o mínimo que debe cumplirse) o de la posición relativa de, por ejemplo, una institución de educación superior con respecto a otras. Los indicadores absolutos dependen de una meta a cumplir (alfabetismo, asistencia escolar, cobertura académica, etc.) mientras que los indicadores relativos ubican la posición de una unidad geográfica con respecto a otras unidades.
    En la administración pública se acostumbra a hablar de una clasificación distinta de los indicadores que obedece al lenguaje propio del área. Allí los indicadores se organizan por ser: *de gestión y de resultado*, *de insumos y productos*, *costos*, *procesos*, *productos* y *resultados*, *insumos*, etc.  
    Existen también los **indicadores de contexto** que, aunque no reflejan de forma directa la situación del sector que se quiere evaluar, son parte del ambiente que afecta la situación social, económica o ambiental y pueden modificar el comportamiento de los fenómenos bajo observación. El producto interno bruto (PIB) per cápita, la tasa de fecundidad y la de crecimiento de la población, entre otros, se consideran como indicadores de contexto.
    
* Desde el tipo de medida o procedimiento estadístico con que se obtiene. Aquí también pueden diferenciarse dos tipos: indicadores objetivos y subjetivos. Los *objetivos* se basan en evidencias externas independientes del informante (como podría ser el nivel educativo de la población), suponiendo que los métodos de captación, procesamiento y divulgación de la información son objetivos. Los subjetivos son juicios, casi siempre en modo y en concepto, y reflejan percepciones y opiniones de la población con respecto a su situación, a la de la sociedad o al país.
    Aquí los indicadores pueden ser clasificados como simples (si se trata de una estadística univariada y/o poco complicada), o sintéticos (si se habla de un agregado que sintetiza la situación global de un sector determinado y que incluye varios componentes del mismo).
    
## Limitaciones de los indicadores 

Entre la problemática que puede presentarse para su identificación e integración está la selección de los que se consideren más adecuados para cada objetivo, existen diferentes actores, como los sectores estadístico, público, privado, social o académico que no comparten las mismas necesidades de información ni persiguen las mismas metas, lo cual dificulta lograr unanimidad en su definición.

Su naturaleza cuantitativo hace que se generen indicadores únicamente de aquello que puede ser medido en cantidad. Des esta forma, su uso presupone que las metas de instituciones y dependencias públicas, así como sus niveles de logro están disponibles, son identificables y cuantificables en planes y programas de gobierno y que no hay contradicciones entre los mismos. 

Si dependen de objetivos que son cambiantes, por ejemplo en cada nueva administración, no sólo se modifica el tipo de indicadores que deben ser empleados, sino también la disponibilidad de datos para conformarlos, lo que conlleva un ajuste permanente de las fuentes de información.

## Marco internacional de los indicadores

Desde mediados del siglo pasado, la ONU empredió la tarea de fomentar la generación de estadísticas e indicadores para medir la calidad de vida en muchos aspectos en los países que conforman esta organización. Poco a poco se han ido conformando infraestructuras estadísticas en cada país que han permitido describir, comparar y evaluar su situación con respecto al mundo. 

Cuenta de este proceso en el campo educativo lo pueden dar diferentes documentos útiles que se relacionan con la construcción de indicadores, dentro de los que se destacan: *Education Indicators: An International Perspective*. [@matheson1996education] de la National Center for Education Statistics, *International education indicators* [@bottani1996oecd] y  *Handbook for internationally comparative education statistics: concepts, standards, definitions and classifications* de la OECD [@organisation2004oecd], *Integrated and Coordinated Implementation of and Follow-up to the Outcomes of the Major United Nations Conferences and Summits in the Economic, Social and Related fields* de la ONU [@assembly2010integrated], *Educational indicators: What's to be measured?* del Banco Mundial [@vos1996educational], *Education Indicators Technical guidelines* y *A Framework for Assessing the Quality of Education Statistics* [@patel2003framework] de la UNESCO [@indicators2009technical], *Summary report of the invitational roundtable on statistical indicators for the quality assessment of higher/tertiary education institutions: Ranking and league table methodologies* de la ASA [@merisotis2002summary] y *Trends in education and training* [@ferriss1978trends], entre otros. Sin embargo, el texo más importante pues constituye el documento teórico y metodológico mejor enfocado es *Statistical indicators for the economic and social sciences*. [@horn1993statistical]

De igual forma en la siguiente página se encuentra material copioso sobre el tema. La Universidad de Harvard dispuso este sitio para reunir dicha información.
<http://guides.library.harvard.edu/c.php?g=309951&p=2070359>

Igualmente la UNESCO mantiene un sitio que almacena información sobre evaluación de educación a nivel mundial:
<http://portal.unesco.org/en/ev.php-URL_ID=34356&URL_DO=DO_TOPIC&URL_SECTION=201.html>

El siguiente título no se encontró y quizás tenga información importante: Johnstone, J.N. (1981) *Indicators of Education Systems* UNESCO, Paris.

La Comisión de Estadística de las Naciones Unidas https://unstats.un.org/home/ ^[Organismo que tiene la función de guiar todas las actividades en la materia de la ONU y colaborar con el Consejo Económico y Social (ECOSOC) y con la Secretaría General de las Naciones Unidas.] está integrada por expertos representantes de las oficinas de estadística de varios países. Esta Comisión se formó con el objetivo de que definiera los indicadores que servirían para realizar el seguimiento de los compromisos que los países asumieron en las cumbres mundiales. Este trabajo ha permitido, por una parte, tener un listado básico de indicadores ligados a las metas de las cumbres y, por otra, llevar a cabo una evaluación del nivel de madurez que, en materia estadística, han alcanzado las naciones.

Actualmente, la Comisión de Estadística cuenta con un conjunto mínimo de 15 indicadores de cada país para el seguimiento de las cumbres mundiales; por su parte, el Comité de Asistencia para el Desarrollo de la OCDE, en cooperación con la ONU, el BM y el FMI, tiene trabajados
21 indicadores de las metas de desarrollo internacional; la Comisión de Desarrollo Sustentable de las Naciones Unidas maneja 57 indicadores, y finalmente la ONU posee un conjunto básico de indicadores sociales que dan cuenta del acceso de la población a los servicios. La OCDE desarrolla y fomenta, entre sus países miembros, una segunda generación de indicadores que muestran no sólo los resultados de la implantación de políticas,sino también los costos, insumos y procesos que participan en la efectividad de las políticas públicas.
 
